version: '3'

volumes:
  mariadb:
    driver: "local"
  redis:
    driver: "local"

services:
# == Workspace Container ==
  workspace:
    build:
      context: ./workspace
      args:
        - NODE_VERSION=stable
        - TZ=UTC
    volumes:
      - ../nuswhispers:/var/www/nuswhispers
    expose:
      - "9001"
    ports:
      - "2222:22"
    tty: true
    links:
      - nginx
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
# == nginx Container ==
  nginx:
    build: ./nginx
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ../nuswhispers:/var/www/nuswhispers
    ports:
      - "8085:80"
    links:
      - php-fpm

# == php-fpm Container ==
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../nuswhispers:/var/www/nuswhispers
    expose:
      - "9000"
      - "9001"
    links:
      - mariadb
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=Docker

# == MariaDB Container ==
  mariadb:
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

# == Redis Container ==
  redis:
    build: ./redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
